# Generated by Django 4.2.5 on 2024-11-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('specs', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='product_images/')),
                ('stock_status', models.CharField(default='In stock', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unique_id', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
